name: style checks

on: [pull_request]

jobs:
  prettier:
    name: prettier has been run on compatible files
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@v2
      - name: check that modified files are prettier
        run: npx prettier $(git diff --diff-filter=ACMR --name-only --relative origin/localdev -- | xargs) -c -u .
  eslint:
    name: frontend linting
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        working-directory: services/ui-src
        run: yarn install
      - name: run eslint
        working-directory: services/ui-src
        run: npx eslint $(git diff --diff-filter=ACMR --name-only --relative origin/master -- . | grep .js$ | xargs)
